[package]
name = "plc_xmlgen"
version = "0.1.0"
edition = "2024"

[dependencies]
plc_ast = { path = "../plc_ast" }
xml = "1.0.0"
rustc-hash = "1.1.0"
chrono = "0.4" #full features required to use the Local struct
itertools = "0.11"
